import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX = (ROOT / 'index.html').read_text(encoding='utf-8')
APP_JS = (ROOT / 'js' / 'app.js').read_text(encoding='utf-8')
ANALYTICS_JS = (ROOT / 'js' / 'analytics.js').read_text(encoding='utf-8')
BRANCHING_JS = (ROOT / 'js' / 'branching.js').read_text(encoding='utf-8')
COACH_JS = (ROOT / 'js' / 'coach.js').read_text(encoding='utf-8')
STUDY_QUIZ_JS = (ROOT / 'js' / 'study-quiz.js').read_text(encoding='utf-8')
RUNTIME_JS = (ROOT / 'js' / 'runtime.js').read_text(encoding='utf-8')
FRONTEND_JS = APP_JS + '\n' + ANALYTICS_JS + '\n' + BRANCHING_JS + '\n' + COACH_JS + '\n' + STUDY_QUIZ_JS + '\n' + RUNTIME_JS


class FrontendSmokeTest(unittest.TestCase):
    def test_expected_assets_are_referenced(self):
        self.assertIn('css/styles.css', INDEX)
        self.assertIn('js/labs-part-1.js', INDEX)
        self.assertIn('js/labs-part-4.js', INDEX)
        self.assertIn('js/analytics.js', INDEX)
        self.assertIn('js/branching.js', INDEX)
        self.assertIn('js/coach.js', INDEX)
        self.assertIn('js/study-quiz.js', INDEX)
        self.assertIn('js/runtime.js', INDEX)
        self.assertIn('js/app.js', INDEX)
        self.assertIn('js/learning-part-1.js', INDEX)
        self.assertIn('js/render.js', INDEX)
        self.assertIn('toggle-incident-mode', INDEX)
        self.assertIn('h-judgment', INDEX)

    def test_exam_prep_section_is_available(self):
        self.assertIn('id="btn-study"', INDEX)
        self.assertIn('id="sidebar-btn-study"', INDEX)
        self.assertIn('id="study-overlay"', INDEX)
        self.assertIn('EXAM_STUDY_GUIDES', FRONTEND_JS)
        self.assertIn('NVIDIA-Certified Associate: AI Infrastructure and Operations', FRONTEND_JS)

    def test_overlay_popouts_are_available(self):
        self.assertIn('id="btn-popout-intro"', INDEX)
        self.assertIn('id="btn-popout-study"', INDEX)
        self.assertIn('id="btn-popout-quiz"', INDEX)
        self.assertIn("openDetachedPanel('introOverlay')", FRONTEND_JS)
        self.assertIn("openDetachedPanel('studyOverlay')", FRONTEND_JS)
        self.assertIn("openDetachedPanel('quizOverlay')", FRONTEND_JS)

    def test_study_quiz_surface_is_available(self):
        self.assertIn('renderStudyGuide', FRONTEND_JS)
        self.assertIn('openStudyGuide', FRONTEND_JS)
        self.assertIn('openStudyLab', FRONTEND_JS)
        self.assertIn('renderStudyLabLinks', FRONTEND_JS)
        self.assertIn('QUIZ = [', FRONTEND_JS)
        self.assertIn('openQuiz', FRONTEND_JS)
        self.assertIn('selectAnswer', FRONTEND_JS)
        self.assertIn('submitQuiz', FRONTEND_JS)
        self.assertIn('resetQuiz', FRONTEND_JS)
        self.assertIn('closeQuiz', FRONTEND_JS)
        self.assertIn('The Chain To Remember', FRONTEND_JS)
        self.assertIn('Submit Answers', FRONTEND_JS)
        self.assertIn('Quiz accuracy', FRONTEND_JS)

    def test_runtime_surface_is_available(self):
        self.assertIn('function loadLab', FRONTEND_JS)
        self.assertIn('function runStep', FRONTEND_JS)
        self.assertIn('function runCurrentStep', FRONTEND_JS)
        self.assertIn('function initApp', FRONTEND_JS)
        self.assertIn('function toggleAppMode', FRONTEND_JS)
        self.assertIn('function toggleThermalView', FRONTEND_JS)
        self.assertIn('function fetchLiveMetrics', FRONTEND_JS)
        self.assertIn('function requestAI_Remediation', FRONTEND_JS)
        self.assertIn('function openIncidentHistory', FRONTEND_JS)
        self.assertIn('LIVE DATACENTER VIEW', FRONTEND_JS)
        self.assertIn('AUTONOMOUS RUNBOOK', FRONTEND_JS)

    def test_reasoning_scorecard_is_available(self):
        self.assertIn('getReasoningScorecardContext', FRONTEND_JS)
        self.assertIn('renderReasoningScorecard', FRONTEND_JS)
        self.assertIn('Reasoning Scorecard', FRONTEND_JS)
        self.assertIn('Assessment Scorecard', FRONTEND_JS)

    def test_differential_diagnosis_is_available(self):
        self.assertIn('DIFFERENTIAL_DIAGNOSIS', APP_JS)
        self.assertIn('renderDifferentialDiagnosis', APP_JS)
        self.assertIn('Differential Diagnosis', APP_JS)
        self.assertIn('What This Is Not', APP_JS)

    def test_incident_mode_is_available(self):
        self.assertIn('incidentMode', APP_JS)
        self.assertIn('setIncidentMode', APP_JS)
        self.assertIn('renderIncidentModeBrief', APP_JS)
        self.assertIn('Incident Brief', APP_JS)

    def test_reasoning_progress_is_available(self):
        self.assertIn('loadReasoningProgress', FRONTEND_JS)
        self.assertIn('recordLabReasoningProgress', FRONTEND_JS)
        self.assertIn('recordQuizReasoningProgress', FRONTEND_JS)
        self.assertIn('recordLabCompletionOutcome', FRONTEND_JS)
        self.assertIn('isLabCompletionClean', FRONTEND_JS)
        self.assertIn('getLabOutcomeSummary', FRONTEND_JS)
        self.assertIn('renderLabOutcomeSummary', FRONTEND_JS)
        self.assertIn('renderReasoningProgressSummary', FRONTEND_JS)
        self.assertIn('Reasoning Progress', FRONTEND_JS)
        self.assertIn('Clean incident finishes', FRONTEND_JS)
        self.assertIn('Next training focus', FRONTEND_JS)
        self.assertIn('Recent risk pattern', FRONTEND_JS)
        self.assertIn('getReasoningFocusRecommendation', FRONTEND_JS)
        self.assertIn('getRecentRiskPattern', FRONTEND_JS)
        self.assertIn('getRecommendedLabsForDomain', FRONTEND_JS)
        self.assertIn('getUniqueLabs', FRONTEND_JS)
        self.assertIn('getRecoveryProgressSignal', FRONTEND_JS)
        self.assertIn('getReasoningProgressReport', FRONTEND_JS)
        self.assertIn('downloadReasoningProgressReport', FRONTEND_JS)
        self.assertIn('Export reasoning report', FRONTEND_JS)
        self.assertIn('Pilot-ready JSON snapshot', FRONTEND_JS)
        self.assertIn('aegis_reasoning_progress', FRONTEND_JS)
        self.assertIn('Start one lab or quiz', FRONTEND_JS)
        self.assertIn('fault isolation', FRONTEND_JS)
        self.assertIn('fabric path', FRONTEND_JS)
        self.assertIn('last compromised lab', FRONTEND_JS)
        self.assertIn('clean finishes in', FRONTEND_JS)
        self.assertIn('Picked because your last compromised run was', FRONTEND_JS)
        self.assertIn('recommended drill', FRONTEND_JS)
        self.assertIn('Incident Outcome', FRONTEND_JS)
        self.assertIn('Recent incident outcomes', FRONTEND_JS)

    def test_ask_aegis_is_available(self):
        self.assertIn('renderAskAegisBlock', FRONTEND_JS)
        self.assertIn('getAskAegisResponse', FRONTEND_JS)
        self.assertIn('Ask Aegis', FRONTEND_JS)
        self.assertIn('What changed?', FRONTEND_JS)
        self.assertIn('Which layer owns this?', FRONTEND_JS)
        self.assertIn('What should I check next?', FRONTEND_JS)
        self.assertIn('Why is this branch scored this way?', FRONTEND_JS)

    def test_consequence_branching_is_available(self):
        self.assertIn('CONSEQUENCE_BRANCHES', FRONTEND_JS)
        self.assertIn('loadBranchingState', FRONTEND_JS)
        self.assertIn('chooseIncidentBranch', FRONTEND_JS)
        self.assertIn('renderConsequenceBranch', FRONTEND_JS)
        self.assertIn('getBranchConsequenceContext', FRONTEND_JS)
        self.assertIn('isBranchDetourPending', FRONTEND_JS)
        self.assertIn('runBranchDetour', FRONTEND_JS)
        self.assertIn('BRANCH_DETOUR_PLAYBOOKS', FRONTEND_JS)
        self.assertIn('ECC Integrity Recovery', FRONTEND_JS)
        self.assertIn('XID Fault Recovery', FRONTEND_JS)
        self.assertIn('NVLink Topology Recovery', FRONTEND_JS)
        self.assertIn('NCCL Fallback Recovery', FRONTEND_JS)
        self.assertIn('Storage Starvation Recovery', FRONTEND_JS)
        self.assertIn('BRANCH_STEP_MODIFIERS', FRONTEND_JS)
        self.assertIn('ECC Revalidation Stage', FRONTEND_JS)
        self.assertIn('Fallback Path Recovery', FRONTEND_JS)
        self.assertIn('ALTERNATE_BRANCH_STEPS', FRONTEND_JS)
        self.assertIn('ALTERNATE_BRANCH_FOLLOWUPS', FRONTEND_JS)
        self.assertIn('ALTERNATE_MAIN_PATH_STEPS', FRONTEND_JS)
        self.assertIn('getAlternateBranchChain', FRONTEND_JS)
        self.assertIn('getMainPathRedirectStep', FRONTEND_JS)
        self.assertIn('ECC Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('ECC Containment Verification', FRONTEND_JS)
        self.assertIn('ECC Containment Decision', FRONTEND_JS)
        self.assertIn('Stack Contract Decision', FRONTEND_JS)
        self.assertIn('GPU Placement Decision', FRONTEND_JS)
        self.assertIn('Scheduler Ownership Decision', FRONTEND_JS)
        self.assertIn('Collective Rejoin Decision', FRONTEND_JS)
        self.assertIn('Fabric Availability Decision', FRONTEND_JS)
        self.assertIn('NVLink Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('CUDA Stack Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Kubernetes Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Slurm Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Collective Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('InfiniBand Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('MIG Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Container Runtime Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Training Pipeline Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('RoCE Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('GDS Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('Monitoring Recovery Checkpoint', FRONTEND_JS)
        self.assertIn('runAlternateBranchStep', FRONTEND_JS)
        self.assertIn('Recovery chain step', FRONTEND_JS)
        self.assertIn('Redirected Main Step', FRONTEND_JS)
        self.assertIn('Containment Recovery', FRONTEND_JS)
        self.assertIn('Transport Recovery', FRONTEND_JS)
        self.assertIn('Route Change Pending', FRONTEND_JS)
        self.assertIn('Branch consequence', FRONTEND_JS)
        self.assertIn('Decision Drill', FRONTEND_JS)
        self.assertIn('Clean incident finish', FRONTEND_JS)
        self.assertIn('Compromised incident finish', FRONTEND_JS)

    def test_frontend_uses_same_origin_api_prefix(self):
        self.assertIn('/api/v1', APP_JS)
        self.assertRegex(APP_JS, r'API_BASE\s*=')

    def test_no_hardcoded_bearer_token_exists(self):
        self.assertNotIn('Bearer ey', APP_JS)
        self.assertNotRegex(APP_JS, re.compile(r'sk-[A-Za-z0-9_-]{20,}'))


if __name__ == '__main__':
    unittest.main()
