/**
 * LABS MODULE: Definitions for the interactive scenarios.
 * Aggregates split LABS data chunks and keeps terminal fixture globals stable.
 */

const LABS = window.AEGIS_LABS = Object.assign(
  {},
  window.AEGIS_LABS_PARTS?.fabric_and_partitioning || {},
  window.AEGIS_LABS_PARTS?.runtime_and_training || {},
  window.AEGIS_LABS_PARTS?.network_and_storage || {},
  window.AEGIS_LABS_PARTS?.operations_and_schedulers || {}
);

const TERMINAL_OUTPUT = {
  topo: [
    {t:'cmd',  v:'$ nvidia-smi topo -m'},
    {t:'dim',  v:'        GPU0  GPU1  GPU2  GPU3  GPU4  GPU5  GPU6  GPU7  CPU Affinity'},
    {t:'good', v:'GPU0     X    NV4   NV4   NV4   NV4   NV4   NV4   NV4   0-63'},
    {t:'good', v:'GPU1    NV4    X    NV4   NV4   NV4   NV4   NV4   NV4   0-63'},
    {t:'good', v:'GPU2    NV4   NV4    X    NV4   NV4   NV4   NV4   NV4   0-63'},
    {t:'good', v:'GPU3    NV4   NV4   NV4    X    NV4   NV4   NV4   NV4   0-63'},
    {t:'good', v:'GPU4    NV4   NV4   NV4   NV4    X    NV4   NV4   NV4   0-63'},
    {t:'good', v:'GPU5    NV4   NV4   NV4   NV4   NV4    X    NV4   NV4   0-63'},
    {t:'good', v:'GPU6    NV4   NV4   NV4   NV4   NV4   NV4    X    NV4   0-63'},
    {t:'good', v:'GPU7    NV4   NV4   NV4   NV4   NV4   NV4   NV4    X    0-63'},
    {t:'good', v:'NV4 = connected via NVLink (4 links) ✓'}
  ],
  nvlink_err: [
    {t:'cmd',  v:'$ nvidia-smi nvlink -e'},
    {t:'good', v:'  Link 0: CRC Flit Error Count:       0  ✓'},
    {t:'good', v:'  Link 1: CRC Flit Error Count:       0  ✓'},
    {t:'good', v:'  Link 2: CRC Flit Error Count:       0  ✓'},
    {t:'good', v:'  Link 3: CRC Flit Error Count:       0  ✓'}
  ],
  benchmark: [
    {t:'cmd',  v:'$ ./nccl-tests/all_reduce_perf -g 8'},
    {t:'good', v:'Avg bus bandwidth    : 187.86 GB/s  ✓ (NVLink 4.0)'}
  ],
  nvlink_fault: [
    {t:'warn', v:'# ⚠ Simulating NVLink failure'},
    {t:'err',  v:'GPU0     X    PHB   PHB   PHB   ← NO NVLink — PCIe only!'},
    {t:'err',  v:'Actual AllReduce:   ~  3 GB/s  (PCIe bottleneck)'}
  ],
  nccl_diag: [
    {t:'cmd',  v:'$ NCCL_DEBUG=INFO torchrun train.py'},
    {t:'err',  v:'NCCL WARN Using network Socket  ← TCP fallback!'},
    {t:'info', v:'Fix: Physical — inspect NVLink cables and NVSwitch ports on failing GPU pair'},
    {t:'info', v:'Run: nvidia-smi nvlink -e -i 0  (check error counters per link)'},
    {t:'dim',  v:'If counters non-zero: isolate GPU, replace NVLink cable or reseat NVSwitch'}
  ],
  mig_enable: [{t:'good', v:'Enabled MIG Mode for GPU 0'}],
  mig_create: [{t:'good', v:'7 MIG instances created (1g.10gb)'}],
  mig_list: [{t:'good', v:'GPU  0  GI 1  CI 0  10GB  MIG 1g.10gb'}],
  mig_assign: [{t:'good', v:'CUDA_VISIBLE_DEVICES=MIG-GPU-0:0:0'}],
  mig_disable: [{t:'good', v:'MIG mode disabled — full GPU restored'}],
  ecc_healthy: [{t:'good', v:'GPU:0       0          0   ✓ ECC clean'}],
  ecc_sbe: [{t:'warn', v:'# ⚠ Simulating degrading memory cells'}],
  ecc_trend: [{t:'err', v:'GPU:0      58          2   ← DRAIN AND RMA NOW'}],
  ecc_xid: [{t:'err', v:'NVRM: Xid 48, Double Bit ECC Error Occurred'}],
  ecc_drain: [{t:'good', v:'node/gpu-node-03 cordoned and drained'}],
  xid48: [{t:'err', v:'[86423.441] NVRM: Xid (PCI:0000:83:00): 48'}],
  xid48_confirm: [{t:'err', v:'Entity  Field 157 (DBE): 2'}],
  xid79: [{t:'err', v:'NVRM: GPU Board RmUninitializeClient: GPU hung'}],
  xid79_reset: [{t:'good', v:'Successfully reset GPU 00000000:43:00.0'}],
  xid74: [{t:'err', v:'XID 74 = NVLink Error — CRC Flit Error Count: 8472'}],
  driver_ver: [{t:'good', v:'NVRM version: 545.23.08'}],
  cuda_ver: [{t:'good', v:'nvcc: NVIDIA (R) Cuda compiler driver 12.3'}],
  torch_check: [{t:'good', v:'CUDA: 12.3 | Available: True'}],
  cuda_mismatch: [{t:'err', v:'PyTorch expects 11.8, Driver supports 12.3'}],
  ngc_fix: [{t:'good', v:'Fixed with NGC: CUDA 12.3, cuDNN 8.9, PyTorch 2.2'}],
  ngc_pull: [{t:'good', v:'Status: Downloaded nvidia/pytorch:24.01-py3'}],
  ngc_run: [{t:'good', v:'GPU accessible from inside container ✓'}],
  ngc_verify: [{t:'good', v:'torch.cuda.device_count(): 8 GPUs'}],
  ngc_train: [{t:'info', v:'[Epoch 1] step=100 loss=2.847 throughput=1234 s/s'}],
  ngc_monitor: [{t:'good', v:'GPU 0: 94% SM utilisation'}],
  ddp_launch: [{t:'good', v:'All 16 ranks connected ✓ (2 nodes × 8 GPUs)'}],
  ddp_fwd: [{t:'info', v:'Forward pass complete on all 16 GPUs'}],
  ddp_bwd: [{t:'info', v:'Backward pass: local gradients computed'}],
  ddp_allreduce: [{t:'good', v:'AllReduce complete via IB NDR ✓'}],
  ddp_update: [{t:'good', v:'optimizer.step() — all replicas identical'}],
  ddp_storage: [{t:'err', v:'nfs0: 100% util — sawtooth bottleneck detected'}],
  nccl_path: [{t:'good', v:'NCCL INFO Using network IB ✓'}],
  ring1: [{t:'info', v:'Round 1/7: Reduce-Scatter phase'}],
  ring2: [{t:'good', v:'Round 14/14: All-Gather complete ✓'}],
  ar_bench: [{t:'good', v:'Avg busbw: 187.8 GB/s (NVLink 4.0)'}],
  ar_fault: [{t:'err', v:'NCCL WARN Using network Socket (TCP Fallback)'}],
  ar_fix: [{t:'good', v:'NCCL INFO Using network IB restored ✓'}],
  ib_stat: [{t:'good', v:'State: Active | Rate: 400 Gb/s NDR'}],
  ib_perfq: [{t:'good', v:'PortXmitDiscards: 0 ✓'}],
  ib_bw: [{t:'good', v:'BW average: 380.94 Gb/sec (95% NDR max)'}],
  ib_fault: [{t:'err', v:'State: Down — Physical connection lost'}],
  ib_diag: [{t:'err', v:'BAD CABLE: node-06 → ibswitch-A port 12'}],
  ib_sweep: [{t:'good', v:'Sweep complete: 95 ports clean, 1 bad isolated'}],
  roce_mtu: [{t:'good', v:'mtu 9000 (jumbo frames) ✓'}],
  roce_pfc: [{t:'good', v:'RX: on | TX: on — PFC lossless enabled ✓'}],
  roce_ecn: [{t:'good', v:'ECN active on priority 3 (RDMA) ✓'}],
  roce_bw: [{t:'good', v:'BW peak: 92.34 GB/s (RoCEv2)'}],
  roce_fault: [{t:'err', v:'rx_pfc_frames: 24891 ← PFC storm detected!'}],
  roce_fix: [{t:'good', v:'ECN threshold lowered — PFC storm resolved ✓'}],
  fb_diag: [{t:'err', v:'NCCL WARN Using network Socket'}],
  fb_env: [{t:'err', v:'NCCL_IB_DISABLE=1 found'}],
  fb_ib: [{t:'good', v:'CA mlx5_0 State: Active ✓'}],
  fb_fix: [{t:'good', v:'unset NCCL_IB_DISABLE ✓'}],
  fb_verify: [{t:'good', v:'NCCL INFO Using network IB restored ✓'}],
  fb_bench: [{t:'good', v:'23× throughput improvement ✓'}],
  stor_gpu: [{t:'err', v:'GPU util: 94% → 4% → 91% (Sawtooth)'}],
  stor_io: [{t:'err', v:'nfs0: 100% util | await 48.2ms'}],
  stor_lustre: [{t:'err', v:'stripe_count: 1 (Lustre bottleneck)'}],
  stor_fix: [{t:'good', v:'stripe_count: 8 OSTs set ✓'}],
  stor_dl: [{t:'good', v:'num_workers=16 set ✓'}],
  stor_verify: [{t:'good', v:'No more sawtooth — throughput +2.3× ✓'}],
  gds_old: [{t:'warn', v:'NVMe → CPU → PCIe → GPU (2 copies)'}],
  gds_new: [{t:'good', v:'NVMe → GPU VRAM (direct DMA - 1 copy)'}],
  gds_verify: [{t:'good', v:'GDS available: 1.8.0 ✓'}],
  gds_bench_old: [{t:'warn', v:'Traditional: 890 MB/s'}],
  gds_bench_new: [{t:'good', v:'GDS: 2.4 GB/s (2.7× faster) ✓'}],
  mon_deploy: [{t:'good', v:'Listening on :9400/metrics ✓'}],
  mon_verify: [{t:'good', v:'dcgm_fi_dev_gpu_util 82 ✓'}],
  mon_prom: [{t:'good', v:'Prometheus scraping 8 nodes every 15s ✓'}],
  mon_grafana: [{t:'good', v:'Dashboard 12239 imported ✓'}],
  mon_alert: [{t:'good', v:'Alert GPUDoublebitECC created ✓'}],
  mon_test: [{t:'err', v:'PagerDuty incident created: GPU 3 DBE ✓'}],
  slurm_submit: [{t:'good', v:'Submitted batch job 99234 ✓'}],
  slurm_queue: [{t:'warn', v:'99234  PENDING  (Priority)'}],
  slurm_pend: [{t:'info', v:'Reason=Priority — start in ~2 hours'}],
  slurm_fair: [{t:'warn', v:'FairShare: 0.034 (Alice usage high)'}],
  slurm_drain: [{t:'warn', v:'gpu-node-05 state changed to DRAIN'}],
  slurm_resume: [{t:'good', v:'gpu-node-05 state changed to IDLE ✓'}],
  k8s_operator: [{t:'good', v:'nvidia-device-plugin READY 1/1 ✓'}],
  k8s_resources: [{t:'good', v:'Allocatable: nvidia.com/gpu: 8 ✓'}],
  k8s_pending: [{t:'err', v:'Insufficient nvidia.com/gpu'}],
  k8s_netpol: [{t:'err', v:'NetworkPolicy blocking port 29500'}],
  k8s_drain: [{t:'good', v:'node/gpu-node-03 drained successfully ✓'}],
  k8s_gang: [{t:'good', v:'PodGroup training-gang Running (16/16) ✓'}]
};

const DMESG_CLEAN = [
  {t:'dim',  v:'[    0.000] Linux version 5.14.0-427.16.1.el9_4.x86_64 (gcc version 11.4.1 20231218)'},
  {t:'dim',  v:'[    0.441] pci 0000:03:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:13:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:23:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:33:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:43:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:53:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:63:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'dim',  v:'[    0.441] pci 0000:73:00.0: [10de:2330] type 00 class 0x030200 (H100 SXM5)'},
  {t:'good', v:'[    0.502] nvidia 0000:03:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.521] nvidia 0000:13:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.539] nvidia 0000:23:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.557] nvidia 0000:33:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.575] nvidia 0000:43:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.593] nvidia 0000:53:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.611] nvidia 0000:63:00.0: enabling device (0000 -> 0002)'},
  {t:'good', v:'[    0.629] nvidia 0000:73:00.0: enabling device (0000 -> 0002)'},
  {t:'info', v:'[    4.101] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  545.23.08  Thu Nov 16 00:00:00 UTC 2023'},
  {t:'info', v:'[    4.204] nvidia-nvswitch: detected 4 NVSwitches (LS10)'},
  {t:'good', v:'[    4.318] nvidia-nvlink: NvLink 4.0 Connected — 900 GB/s bidirectional per link  ✓'},
  {t:'good', v:'[    4.502] nvidia-nvswitch: all 8 GPUs fully meshed via NVSwitch fabric  ✓'},
  {t:'info', v:'[    5.012] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms 545.23.08'},
  {t:'dim',  v:'[    5.234] NVRM: GPU Board Serial Number: [N/A]'},
  {t:'good', v:'[   12.441] nvidia 0000:03:00.0: irq 151 for MSI/MSI-X  ✓'},
  {t:'good', v:'[   12.458] nvidia 0000:13:00.0: irq 167 for MSI/MSI-X  ✓'},
  {t:'good', v:'[   12.475] nvidia 0000:23:00.0: irq 183 for MSI/MSI-X  ✓'},
  {t:'good', v:'[   15.001] nvidia-peermem: module loaded, version 1.4'},
  {t:'good', v:'[   15.441] nvidia-fs: nvidia_fs init successful, version=2.17.0 (GPUDirect Storage ready)  ✓'},
  {t:'good', v:'[   16.020] mlx5_core 0000:c1:00.0: firmware version 28.39.1002 (ConnectX-7 NDR400)'},
  {t:'good', v:'[   16.088] mlx5_core 0000:c1:00.1: firmware version 28.39.1002 (ConnectX-7 NDR400)'}
];

const DCGM_CLEAN = [
  {t:'dim',  v:'# dcgmi dmon -e 100,101,110,140,155,156,157,206 -d 1000'},
  {t:'dim',  v:'#           Utiliz  MemUtil  FBUsed   Temp   Power   SBE     DBE     XID'},
  {t:'dim',  v:'#Entity     (%)     (%)      (MiB)    (°C)   (W)     (cnt)   (cnt)   (cnt)'},
  {t:'good', v:' GPU 0       82      68       43622    71     418     0       0       0'},
  {t:'good', v:' GPU 1       79      65       42187    69     411     0       0       0'},
  {t:'good', v:' GPU 2       85      71       45056    73     432     0       0       0'},
  {t:'good', v:' GPU 3       81      67       43008    70     421     0       0       0'},
  {t:'good', v:' GPU 4       83      69       44032    72     425     0       0       0'},
  {t:'good', v:' GPU 5       80      66       42496    70     415     0       0       0'},
  {t:'good', v:' GPU 6       84      70       44544    71     428     0       0       0'},
  {t:'good', v:' GPU 7       82      68       43520    71     419     0       0       0'},
  {t:'dim',  v:''},
  {t:'dim',  v:'# dcgmi health -g 0 --check'},
  {t:'good', v:'Overall Health: Healthy'},
  {t:'good', v:'  GPU 0 : Healthy  |  GPU 1 : Healthy  |  GPU 2 : Healthy  |  GPU 3 : Healthy'},
  {t:'good', v:'  GPU 4 : Healthy  |  GPU 5 : Healthy  |  GPU 6 : Healthy  |  GPU 7 : Healthy'},
  {t:'dim',  v:''},
  {t:'dim',  v:'# dcgmi nvlink --link-status -g 0'},
  {t:'good', v:'  GPU 0 - Link  0: Active  bw=900 GB/s  ✓   CRC Errs: 0   Replay: 0'},
  {t:'good', v:'  GPU 0 - Link  1: Active  bw=900 GB/s  ✓   CRC Errs: 0   Replay: 0'},
  {t:'good', v:'  GPU 1 - Link  0: Active  bw=900 GB/s  ✓   CRC Errs: 0   Replay: 0'},
  {t:'good', v:'  GPU 2 - Link  0: Active  bw=900 GB/s  ✓   CRC Errs: 0   Replay: 0'}
];
