/**
 * EXTENDED QUIZ BANK — merged into QUIZ by study-quiz.js at load.
 * Each item: {domain: 1|2|3, q, opts, ans, exp, correct, wrong:{optIdx: feedback}}
 * Domains follow the NCA-AIIO blueprint: 1=Essential AI Knowledge (38%),
 * 2=AI Infrastructure (40%), 3=AI Operations (22%).
 * Authored from the official blueprint topics and this platform's labs —
 * no exam dumps or leaked questions.
 */
window.AEGIS_QUIZ_BANK = [

// ============ DOMAIN 1 — ESSENTIAL AI KNOWLEDGE ============
{domain:1, q:"Which relationship between AI, machine learning, and deep learning is correct?",
 opts:["They are three unrelated fields","Deep learning contains machine learning, which contains AI","AI contains machine learning, which contains deep learning","Machine learning and deep learning are synonyms inside AI"],
 ans:2, exp:"AI is the broadest goal (machines doing tasks that need intelligence), ML is the subset that learns patterns from data instead of hand-written rules, and DL is the subset of ML that uses many-layered neural networks.",
 correct:"Right — nested subsets: AI ⊃ ML ⊃ DL.",
 wrong:{0:"They are nested, not unrelated: DL is a kind of ML, and ML is a kind of AI.",1:"That inverts the hierarchy — AI is the outermost category, not the innermost.",3:"ML and DL are not synonyms: DL is the specific ML family that uses deep neural networks."}},

{domain:1, q:"What property of neural-network workloads makes GPUs a better fit than CPUs?",
 opts:["Neural networks need very high single-thread clock speeds","The math is mostly large matrix operations that parallelize across thousands of cores","Neural networks require large CPU caches","GPUs have more system RAM than CPUs"],
 ans:1, exp:"Training and inference are dominated by matrix multiplications on huge tensors — the same simple operation repeated across independent data. Thousands of small GPU cores execute these in parallel, while a CPU's few fast cores work through them serially.",
 correct:"Exactly — massively parallel matrix math is the whole story.",
 wrong:{0:"Single-thread speed is a CPU strength, but neural nets don't need one fast lane — they need thousands of parallel lanes.",2:"Cache size helps CPUs generally; it isn't why deep learning moved to GPUs.",3:"GPUs typically have less memory than system RAM — their advantage is parallel compute and memory bandwidth, not capacity."}},

{domain:1, q:"What are Tensor Cores?",
 opts:["GPU cores reserved for graphics shading","Dedicated hardware units that accelerate matrix multiply-accumulate at reduced precision","The scheduling units that assign warps to SMs","On-die memory caches for tensors"],
 ans:1, exp:"Tensor Cores are specialized circuits inside each SM that perform small matrix multiply-accumulate operations in one step, typically at FP16/BF16/FP8 with FP32 accumulation — the operation deep learning spends most of its time on.",
 correct:"Correct — purpose-built matrix engines, the reason modern GPUs dominate AI math.",
 wrong:{0:"Graphics shading uses the general CUDA cores; Tensor Cores exist specifically for matrix math.",2:"Warp scheduling is a separate SM function; Tensor Cores execute math, they don't schedule it.",3:"They are compute units, not caches — memory is served by HBM and the cache hierarchy."}},

{domain:1, q:"Why does deep learning commonly use FP16 or FP8 precision instead of FP64?",
 opts:["Lower precision halves accuracy but saves money","Neural networks tolerate reduced precision, so smaller numbers mean more math per second and less memory traffic","FP64 is not supported on GPUs","Regulators require reduced precision for AI"],
 ans:1, exp:"Model weights and activations don't need 64-bit exactness — training converges fine with mixed precision. Smaller number formats let Tensor Cores do several times more operations per second and move half (or a quarter) of the bytes.",
 correct:"Right — precision is traded where the model doesn't need it, for large speed and memory wins.",
 wrong:{0:"Done properly (mixed precision with FP32 accumulation), accuracy is essentially preserved — that's why the technique is standard.",2:"GPUs support FP64; it's just slower and unnecessary for most deep learning.",3:"No regulation is involved — it's an engineering trade-off."}},

{domain:1, q:"Which factor set best explains why AI adoption accelerated in the last decade?",
 opts:["Cheaper disks, faster CPUs, better antivirus","Explosion of data, accelerated computing, better algorithms (transformers), and pretrained models","Government mandates and standardized programming languages","Quantum computers becoming widely available"],
 ans:1, exp:"Four reinforcing drivers: far more data to learn from, GPU computing making training tractable, algorithmic advances like the transformer, and cloud access plus pretrained models lowering the barrier to entry.",
 correct:"Correct — data, compute, algorithms, and accessibility reinforce each other.",
 wrong:{0:"General IT improvements didn't unlock deep learning — parallel accelerated compute did.",2:"No mandate drove adoption; economics and capability did.",3:"Quantum computers remain experimental and played no role in the AI boom."}},

{domain:1, q:"A hospital uses AI to flag tumors in radiology scans. Which AI workload class is this?",
 opts:["Recommender system","Computer vision (image classification/segmentation)","Speech recognition","Reinforcement learning for robotics"],
 ans:1, exp:"Analyzing medical images to find tumors is computer vision — one of the highest-impact enterprise AI use cases, alongside recommenders (retail), fraud detection (finance), and conversational AI.",
 correct:"Right — medical imaging is a classic computer-vision deployment.",
 wrong:{0:"Recommenders rank items for users (products, content) — nothing is being ranked here.",2:"There is no audio involved.",3:"Nothing is learning by trial-and-error control — the model classifies images."}},

{domain:1, q:"What is generative AI, as distinct from discriminative AI?",
 opts:["AI that runs on generators during power failures","Models that create new content (text, images, code) rather than only classifying inputs","Any model trained on more than one GPU","AI that generates its own training hardware requirements"],
 ans:1, exp:"Discriminative models answer 'which label?' (spam or not, tumor or not). Generative models learn the distribution of the data well enough to produce new samples from it — LLM text, synthesized images, generated code.",
 correct:"Correct — generation of new content vs classification of existing content.",
 wrong:{0:"Power infrastructure is unrelated to the term.",2:"GPU count has nothing to do with the generative/discriminative distinction.",3:"Sizing requirements are an operations concern, not a model class."}},

{domain:1, q:"What is an LLM (large language model)?",
 opts:["A database of all sentences on the internet","A transformer network trained on massive text corpora to predict tokens, enabling language understanding and generation","A rule-based chatbot with many hand-written responses","A compression format for text files"],
 ans:1, exp:"LLMs are deep transformer networks trained on enormous text datasets to predict the next token. That simple objective, at scale, yields general language capabilities — the foundation of modern chat assistants.",
 correct:"Right — transformers plus token prediction at massive scale.",
 wrong:{0:"It stores learned weights, not the text itself — the training data is not kept verbatim inside.",2:"Rule-based chatbots are the pre-ML approach LLMs replaced.",3:"LLMs are models, not file formats."}},

{domain:1, q:"During model training, what is a 'weight'?",
 opts:["The physical mass of the GPU","A learnable numeric parameter the network adjusts to reduce prediction error","The electricity consumed per epoch","The size of the dataset in gigabytes"],
 ans:1, exp:"Weights are the millions-to-billions of numbers inside the network. Training repeatedly nudges them (using gradients) so the model's outputs get closer to the desired answers. The finished set of weights IS the trained model.",
 correct:"Correct — weights are the parameters that learning adjusts; the trained model is its weights.",
 wrong:{0:"Hardware mass is irrelevant — 'weight' is a mathematical term here.",2:"Power draw matters to operators but is not what a weight is.",3:"Dataset size is measured separately; weights live inside the model."}},

{domain:1, q:"What does a gradient tell the training process?",
 opts:["The slope of the datacenter floor","For each weight, the direction and amount to adjust it to reduce the loss","The GPU temperature gradient across the heatsink","How fast data flows from storage"],
 ans:1, exp:"After each batch, backpropagation computes the gradient of the loss with respect to every weight — a per-weight correction signal. The optimizer then steps each weight slightly against its gradient. In multi-GPU training these gradients are what all-reduce exchanges.",
 correct:"Right — the per-weight correction signal, and exactly what all-reduce synchronizes.",
 wrong:{0:"Physical slopes are not involved.",2:"Thermal gradients are real but belong to facilities, not learning.",3:"Storage throughput is a different pipeline stage."}},

{domain:1, q:"What is an epoch in training?",
 opts:["One complete pass through the entire training dataset","One second of GPU time","One update of a single weight","The time between two checkpoints"],
 ans:0, exp:"An epoch means the model has seen every training sample once. Training typically runs many epochs, with the dataset divided into batches, and progress is often reported per epoch.",
 correct:"Correct — one full pass over the dataset.",
 wrong:{1:"Wall-clock time varies enormously; an epoch is defined by data coverage, not seconds.",2:"Weights update every batch — thousands of times per epoch.",3:"Checkpoint cadence is an operational choice, unrelated to epochs by definition."}},

{domain:1, q:"Why does increasing batch size (until memory limits) usually improve GPU throughput?",
 opts:["It reduces the model's parameter count","More samples processed together keeps the GPU's parallel cores fully occupied per step","It lowers the network bandwidth needed","It reduces GPU temperature"],
 ans:1, exp:"A GPU has thousands of cores; small batches leave many idle. Larger batches turn the workload into bigger matrix operations that saturate the hardware — until you run out of GPU memory.",
 correct:"Right — bigger batches mean bigger matrix ops, keeping the parallel hardware busy.",
 wrong:{0:"Model size is unchanged by batch size.",2:"Gradient sync traffic is unchanged or slightly amortized, but that's secondary — occupancy is the point.",3:"A busier GPU usually runs hotter, not cooler."}},

{domain:1, q:"Which best describes inference serving compared with training?",
 opts:["Long-running, throughput-oriented, huge batch sizes","Short-lived requests, latency-sensitive, often small dynamic batches, scaled across many replicas","Only runs on CPUs","Requires InfiniBand between all replicas"],
 ans:1, exp:"Serving answers live requests: latency budgets in milliseconds, unpredictable arrival rates, dynamic batching to balance latency vs throughput, and horizontal scaling. Training is the opposite profile — long jobs judged on throughput.",
 correct:"Correct — latency-driven, elastic, many small requests.",
 wrong:{0:"That's the training profile, not serving.",2:"GPUs commonly serve inference too — especially LLMs, where they're essential.",3:"Replicas serve independent requests; they don't need a training-style fabric."}},

{domain:1, q:"What does TensorRT do to a trained model?",
 opts:["Retrains it on new data","Optimizes it for inference: precision reduction, layer fusion, kernel selection for the target GPU","Converts it into a spreadsheet","Distributes it across Slurm nodes"],
 ans:1, exp:"TensorRT is NVIDIA's inference optimizer: it takes a trained model and compiles a faster runtime engine using techniques like FP16/INT8/FP8 quantization, fusing layers, and choosing optimal kernels for the specific GPU.",
 correct:"Right — an inference compiler/optimizer, often worth multiples of throughput.",
 wrong:{0:"Training is finished before TensorRT enters — it never changes what the model learned.",2:"Model formats are binary engines, not spreadsheets.",3:"Job scheduling belongs to Slurm/Kubernetes, not TensorRT."}},

{domain:1, q:"What is NVIDIA Triton Inference Server?",
 opts:["A GPU cooling product","A server that loads models from multiple frameworks and serves them over HTTP/gRPC with batching, concurrency, and metrics","A replacement for the CUDA driver","A BIOS utility for DGX systems"],
 ans:1, exp:"Triton is the standard open-source serving layer: one process that hosts PyTorch/TensorFlow/ONNX/TensorRT models, exposes a uniform API, performs dynamic batching, runs models concurrently, and exports Prometheus metrics.",
 correct:"Correct — the production serving layer above your optimized models.",
 wrong:{0:"No relation to cooling.",2:"It runs on top of CUDA; it doesn't replace any driver.",3:"It's a userspace service, not firmware."}},

{domain:1, q:"What are NVIDIA NIM microservices?",
 opts:["Network interface modules for InfiniBand","Prebuilt, containerized inference microservices exposing standard APIs for popular models","A monitoring agent for DCGM","NVLink cable management hardware"],
 ans:1, exp:"NIM packages a model plus its optimized runtime (TensorRT-LLM, Triton) into a ready-to-run container with standard APIs — deploy a production-grade LLM endpoint without building the serving stack yourself.",
 correct:"Right — inference-in-a-box containers with standard APIs.",
 wrong:{0:"Despite the acronym flavor, NIM is software, not a network card.",2:"Monitoring is DCGM's job; NIM serves models.",3:"No hardware involved — it's a container."}},

{domain:1, q:"Which CUDA-X library provides GPU-accelerated deep learning primitives such as convolutions?",
 opts:["cuBLAS","cuDNN","NCCL","cuFFT"],
 ans:1, exp:"cuDNN implements the deep-learning building blocks (convolutions, attention, normalization, activations) that frameworks call under the hood. cuBLAS covers general linear algebra, NCCL covers multi-GPU communication, cuFFT covers Fourier transforms.",
 correct:"Correct — cuDNN is the deep-learning primitives library.",
 wrong:{0:"cuBLAS is general matrix/linear algebra — close, but the DL-specific primitives live in cuDNN.",2:"NCCL moves data between GPUs; it computes nothing.",3:"cuFFT accelerates Fourier transforms — signal processing, not DL layers."}},

{domain:1, q:"What is RAPIDS?",
 opts:["A GPU firmware update tool","A suite of GPU-accelerated data science libraries (cuDF, cuML) mirroring pandas/scikit-learn APIs","NVIDIA's cloud gaming service","A fast InfiniBand routing protocol"],
 ans:1, exp:"RAPIDS moves the data-preparation and classical-ML stages onto GPUs: cuDF is a pandas-like dataframe library, cuML mirrors scikit-learn. It closes the gap where data prep on CPUs starves expensive GPUs.",
 correct:"Right — GPU data science with familiar pandas/sklearn-style APIs.",
 wrong:{0:"Firmware tools are separate; RAPIDS is a data-science stack.",2:"Cloud gaming is GeForce NOW.",3:"Networking protocols are unrelated — the name refers to fast data processing."}},

{domain:1, q:"What is NGC (NVIDIA GPU Cloud) primarily used for?",
 opts:["Renting physical GPUs by the hour","A catalog of tested, optimized containers, pretrained models, and Helm charts","A social network for ML engineers","Overclocking datacenter GPUs"],
 ans:1, exp:"NGC is NVIDIA's registry: version-matched framework containers (PyTorch with the right CUDA/cuDNN), pretrained models, and deployment charts. Pulling from NGC replaces fragile hand-built dependency stacks.",
 correct:"Correct — the known-good software catalog, not a compute rental service.",
 wrong:{0:"Despite the name, NGC hosts software artifacts, not rentable GPUs.",2:"It's a registry, not a community platform.",3:"Overclocking is not an NGC function."}},

{domain:1, q:"What is NVIDIA AI Enterprise?",
 opts:["A GPU trade-in program","A supported, certified software suite (frameworks, Triton, NIM, tools) licensed for production AI on mainstream servers and clouds","A cryptocurrency mining stack","An internal NVIDIA HR system"],
 ans:1, exp:"AI Enterprise is the commercial, supported packaging of NVIDIA's AI software — certified against common servers, hypervisors, and clouds, with enterprise support and long-term stability guarantees. It's also the licensing vehicle for vGPU AI workloads.",
 correct:"Right — the enterprise-supported software layer with certification and support contracts.",
 wrong:{0:"Hardware programs are separate from this software suite.",2:"Mining is unrelated.",3:"It's a customer product, not internal tooling."}},

{domain:1, q:"In the AI lifecycle, what happens in the data-preparation stage?",
 opts:["Model weights are quantized","Raw data is collected, cleaned, labeled, and transformed into training-ready features","GPUs are installed in racks","Inference endpoints are load-tested"],
 ans:1, exp:"Before any training: gather data, remove noise and duplicates, label it, and transform it into tensors. Poor data preparation caps model quality no matter how much compute follows — and slow prep pipelines starve GPUs.",
 correct:"Correct — and its quality bounds everything downstream.",
 wrong:{0:"Quantization is the optimization stage, after training.",2:"Racking hardware is infrastructure, not the data pipeline.",3:"Load-testing happens at deployment, the other end of the lifecycle."}},

{domain:1, q:"Which lifecycle ordering is correct?",
 opts:["Deploy → train → prepare data → monitor","Prepare data → train → optimize → deploy → monitor","Optimize → monitor → train → deploy","Monitor → prepare data → deploy → train"],
 ans:1, exp:"Data preparation feeds training; the trained model is optimized (TensorRT, quantization) for serving; deployment puts it behind an endpoint (Triton/NIM); monitoring watches quality and utilization — and feeds the next data cycle.",
 correct:"Right — and monitoring loops back into new data for retraining.",
 wrong:{0:"You can't deploy a model that hasn't been trained on prepared data.",2:"There is nothing to optimize before training produces a model.",3:"Monitoring without a deployed model has nothing to watch."}},

{domain:1, q:"Why is fine-tuning a pretrained model often preferred over training from scratch?",
 opts:["Fine-tuning always produces smaller models","It reuses general knowledge already learned, needing far less data and compute for the target task","From-scratch training is prohibited by license","Fine-tuned models don't need GPUs"],
 ans:1, exp:"A pretrained foundation model already encodes general language or vision knowledge from massive training runs. Fine-tuning adapts it to a specific task with a fraction of the data, time, and cost of starting over.",
 correct:"Correct — inherit the expensive general learning, pay only for the specialization.",
 wrong:{0:"Size typically stays the same; the weights are adjusted, not compressed.",2:"Licensing varies by model but doesn't forbid from-scratch training.",3:"Fine-tuning is itself GPU-intensive training, just much shorter."}},

{domain:1, q:"What is NVIDIA Base Command Manager used for?",
 opts:["Managing employee access badges","Provisioning, managing, and monitoring AI clusters (nodes, images, Slurm/Kubernetes, health)","Compiling CUDA kernels faster","Designing GPU silicon"],
 ans:1, exp:"BCM is cluster management software: bare-metal provisioning of nodes, software image management, workload-manager integration (Slurm/K8s), and cluster health monitoring — the operational glue of DGX clusters and SuperPODs.",
 correct:"Right — the cluster provisioning and management layer.",
 wrong:{0:"Physical security is out of scope.",2:"Compilation is nvcc's job.",3:"Chip design happens long before cluster software."}},

{domain:1, q:"What role does the GPU driver play in the AI software stack?",
 opts:["It renders the desktop only","It is the kernel-level layer that exposes the GPU to software; CUDA runtimes and frameworks depend on a compatible driver version","It replaces the operating system","It is only needed for graphics workloads"],
 ans:1, exp:"The driver sits between the OS kernel and everything else. Each CUDA version requires a minimum driver version; most 'framework can't see the GPU' incidents are driver/CUDA mismatches — which is why NGC containers pin compatible stacks.",
 correct:"Correct — the foundation layer whose version compatibility everything else rides on.",
 wrong:{0:"Datacenter GPUs often render nothing — the driver's compute role is what matters here.",2:"It's a kernel module inside the OS, not an OS itself.",3:"Compute workloads need it just as much as graphics ever did."}},

{domain:1, q:"Which industry pairing of AI use cases is most accurate?",
 opts:["Finance: fraud detection · Retail: recommender systems · Manufacturing: visual inspection","Finance: video rendering · Retail: protein folding · Manufacturing: chatbots only","Healthcare: ad targeting · Automotive: spreadsheets · Retail: chip design","All industries use AI only for email filtering"],
 ans:0, exp:"The flagship deployments: fraud/risk models in finance, recommenders in retail and media, defect detection and robotics in manufacturing — plus medical imaging in healthcare and perception models in automotive.",
 correct:"Right — those are the signature use cases per industry.",
 wrong:{1:"Those pairings are scrambled — each industry's flagship use case matches its data and problem type.",2:"Scrambled again: healthcare leads with imaging, automotive with perception/autonomy.",3:"Email filtering is one small classical application, nowhere near the breadth of enterprise AI."}},

{domain:1, q:"What is the transformer architecture's key mechanism that enabled modern LLMs?",
 opts:["Convolution over image patches","Self-attention, letting every token weigh its relationship to every other token in parallel","Random forests of decision trees","Exact database lookup"],
 ans:1, exp:"Self-attention lets the model relate all positions in a sequence simultaneously — capturing long-range context — and, critically, parallelizes across the sequence, which maps perfectly onto GPUs. That combination unlocked scaling to today's LLMs.",
 correct:"Correct — parallel self-attention is both the capability and the GPU-friendliness.",
 wrong:{0:"Convolutions power CNNs for vision; transformers replaced recurrence with attention.",2:"Random forests are classical ML, unrelated to LLMs.",3:"LLMs generate from learned weights, not lookups."}},

{domain:1, q:"Why do LLM inference deployments need significant GPU memory even though no training occurs?",
 opts:["The model's billions of weights plus the attention KV-cache for each active sequence must reside in GPU memory","Inference stores the entire internet in VRAM","GPU memory is only used for logging","They don't — LLM inference runs comfortably in 1 GB"],
 ans:0, exp:"Serving must hold all model weights (tens of GB for large models, even quantized) plus a KV-cache that grows with every concurrent sequence and its context length. Memory capacity often decides how many requests a GPU can serve.",
 correct:"Right — weights + per-request KV-cache is the serving memory equation.",
 wrong:{1:"Models store learned parameters, not raw source text.",2:"Logging is negligible; the weights and cache dominate.",3:"Large-model serving is memory-hungry — capacity planning is a real operations task."}},

{domain:1, q:"What does 'GPU-accelerated computing' mean in NVIDIA's platform terminology?",
 opts:["Overclocking GPUs beyond specification","Offloading the parallelizable portions of an application to the GPU while the CPU runs the serial portions","Replacing all CPUs in a datacenter","Using GPUs exclusively for graphics"],
 ans:1, exp:"The heterogeneous model: the CPU orchestrates and runs serial logic while compute-dense parallel kernels (matrix math, data transforms) execute on the GPU. CUDA is the platform that makes this split programmable.",
 correct:"Correct — CPU and GPU each doing what they're best at.",
 wrong:{0:"Acceleration comes from architecture, not overclocking.",2:"CPUs remain essential for serial work and orchestration.",3:"The compute (non-graphics) use is precisely what 'accelerated computing' refers to."}},

{domain:1, q:"A data-prep pipeline in pandas takes 6 hours per day while the training GPUs sit idle. Which NVIDIA library directly targets this problem?",
 opts:["cuDF (RAPIDS)","NCCL","TensorRT","DOCA"],
 ans:0, exp:"cuDF is the RAPIDS dataframe library with a pandas-like API that runs transforms on the GPU — often collapsing hours of CPU wrangling into minutes and keeping expensive training hardware fed.",
 correct:"Right — move the dataframe work onto the GPU with cuDF.",
 wrong:{1:"NCCL accelerates GPU-to-GPU communication in training, not dataframe processing.",2:"TensorRT optimizes inference, downstream of this problem.",3:"DOCA programs DPUs for infrastructure offload — a different layer entirely."}},

{domain:1, q:"What distinguishes DGX systems from HGX platforms?",
 opts:["DGX is software, HGX is hardware","DGX is NVIDIA's fully integrated GPU server product; HGX is the GPU baseboard platform OEMs build their own servers around","HGX is newer and replaces DGX","They are identical products with different stickers"],
 ans:1, exp:"DGX ships as a complete validated system — GPUs, NVLink, networking, software stack. HGX supplies the GPU+NVSwitch baseboard so Dell/Supermicro/HPE and others can engineer their own chassis around it.",
 correct:"Correct — integrated appliance vs OEM building block.",
 wrong:{0:"Both are hardware; the difference is who integrates the full server.",2:"They're parallel offerings for different buyers, not generations.",3:"Different products for different procurement models."}},

// ============ DOMAIN 2 — AI INFRASTRUCTURE ============
{domain:2, q:"What is NVLink?",
 opts:["An Ethernet standard for GPU servers","A high-bandwidth, low-latency direct GPU-to-GPU interconnect, far faster than PCIe","NVIDIA's driver update service","A fiber-optic wall plug"],
 ans:1, exp:"NVLink connects GPUs directly at hundreds of GB/s per GPU (900 GB/s on H100), letting multi-GPU jobs exchange gradients without squeezing through PCIe. It's the express lane inside DGX/HGX systems.",
 correct:"Right — the dedicated GPU-to-GPU highway inside a node.",
 wrong:{0:"Ethernet connects servers to networks; NVLink connects GPUs to each other.",2:"Software services are unrelated to this hardware link.",3:"It's a board-level interconnect, not building wiring."}},

{domain:2, q:"What does NVSwitch add to NVLink?",
 opts:["Wireless GPU connectivity","A switch fabric so every GPU in the system reaches every other GPU at full NVLink bandwidth simultaneously","Automatic driver installation","Power distribution to the GPUs"],
 ans:1, exp:"Point-to-point NVLink alone can't fully connect 8 GPUs at full speed. NVSwitch chips form a crossbar so all GPUs communicate at full bandwidth at once — essential for efficient all-reduce across the whole node.",
 correct:"Correct — all-to-all full bandwidth instead of limited point-to-point pairs.",
 wrong:{0:"All NVLink connectivity is wired through the baseboard.",2:"Software deployment is unrelated.",3:"Power comes from the PSU/busbar, not NVSwitch."}},

{domain:2, q:"An 8-GPU training job inside one DGX node primarily uses which path for gradient exchange, and which for inter-node exchange?",
 opts:["PCIe inside, WiFi outside","NVLink/NVSwitch inside the node; InfiniBand or RoCE between nodes","SATA inside, USB outside","NVSwitch for both intra- and inter-node"],
 ans:1, exp:"Within a node, NCCL routes collectives over NVLink/NVSwitch. Crossing nodes, traffic moves over the RDMA fabric — InfiniBand or RoCE — ideally with GPUDirect RDMA so the NIC reads GPU memory directly.",
 correct:"Right — NVLink inside the box, RDMA fabric between boxes.",
 wrong:{0:"WiFi could not carry a training fabric's bandwidth or latency needs.",2:"SATA/USB are storage/peripheral buses, orders of magnitude too slow.",3:"NVSwitch fabric stays inside the chassis (NVLink Switch systems exist, but the standard answer for clusters is the IB/RoCE fabric)."}},

{domain:2, q:"What is RDMA and why do AI fabrics depend on it?",
 opts:["A RAID mode for GPU disks","Remote Direct Memory Access — NICs move data between servers' memory without CPU involvement, giving microsecond latency at line rate","A driver-management API","Redundant DNS for ML clusters"],
 ans:1, exp:"RDMA lets the network card write directly into remote memory, bypassing kernels and CPU copies. Collective operations across hundreds of GPUs live and die by this — it's the core of both InfiniBand and RoCE.",
 correct:"Correct — kernel-bypass memory-to-memory transfers are what make the fabric fast.",
 wrong:{0:"Storage arrays are unrelated to this networking concept.",2:"It's a hardware data-path capability, not a management API.",3:"DNS resolution has nothing to do with it."}},

{domain:2, q:"What is GPUDirect RDMA specifically?",
 opts:["A marketing name for PCIe","The NIC reads/writes GPU memory directly over PCIe, skipping the host-memory bounce buffer","GPUs sending email directly","Direct water cooling for network cards"],
 ans:1, exp:"Without it, GPU data headed for the network detours through system RAM. GPUDirect RDMA lets the InfiniBand/RoCE NIC DMA straight into GPU memory — cutting latency and freeing CPU and memory bandwidth.",
 correct:"Right — NIC-to-GPU-memory directly, no host bounce.",
 wrong:{0:"It's a capability layered above PCIe transactions, not a rebrand.",2:"Email is not involved.",3:"Cooling is a different GPUDirect-unrelated concern."}},

{domain:2, q:"Why does RoCE require a lossless Ethernet configuration (PFC/ECN)?",
 opts:["To encrypt training data","RDMA transport recovers poorly from drops, so switches must pause/mark traffic instead of dropping packets under congestion","To reduce cable costs","Because Ethernet frames are too small otherwise"],
 ans:1, exp:"RoCE carries RDMA over Ethernet. A single dropped packet triggers expensive recovery that stalls collectives, so Priority Flow Control pauses traffic classes and ECN marks congestion early — making Ethernet behave losslessly.",
 correct:"Correct — pause and mark instead of drop, because RDMA hates loss.",
 wrong:{0:"PFC/ECN manage congestion, not confidentiality.",2:"Cabling costs are unchanged.",3:"Frame size (MTU matters too) is a separate tuning knob from losslessness."}},

{domain:2, q:"What is a 'rail-optimized' network design in AI clusters?",
 opts:["Mounting switches on rails for easy service","Each GPU's dedicated NIC connects to its own switch plane (rail), so collective traffic from same-ranked GPUs never contends across rails","Using train networks for data transport","Running cables along the ceiling"],
 ans:1, exp:"In DGX-class nodes each GPU pairs with its own high-speed NIC; rail-optimized fabrics wire NIC k of every node to switch plane k. NCCL's traffic patterns then stay within planes, minimizing congestion at scale.",
 correct:"Right — one switch plane per GPU/NIC index keeps collective flows separated.",
 wrong:{0:"Rack hardware is not the meaning here.",2:"'Rail' refers to network planes, not railways.",3:"Cable routing aesthetics don't define the architecture."}},

{domain:2, q:"What does the InfiniBand subnet manager do?",
 opts:["Assigns email subnets","Discovers the fabric topology, assigns addresses (LIDs), and programs switch forwarding tables","Manages GPU BIOS versions","Rents IP addresses from the cloud"],
 ans:1, exp:"InfiniBand is centrally managed: the subnet manager (e.g., UFM or opensm) sweeps the fabric, addresses every port, and computes routes. If it's down or misconfigured, ports stay in INIT and never reach Active.",
 correct:"Correct — the fabric's brain; ports stuck in INIT usually point at it.",
 wrong:{0:"Email infrastructure is unrelated.",2:"Firmware management is a separate tool's job.",3:"There's no DHCP-style leasing from clouds in IB."}},

{domain:2, q:"Roughly how much power does a DGX H100 node draw at full load, and why does it matter?",
 opts:["~500 W — a standard wall outlet suffices","~10 kW — a handful of nodes exhausts a typical rack power budget","~100 kW per node","Power draw is irrelevant to cluster design"],
 ans:1, exp:"With 8×700 W GPUs plus CPUs, NICs, and fans, a DGX H100 draws ~10.2 kW. Rack feeds of 20–40 kW therefore hold only 2–4 nodes — power, not space, usually caps AI density.",
 correct:"Right — ~10 kW/node means power budgets, not rack units, set density.",
 wrong:{0:"That's two orders of magnitude short — these are the densest servers in the building.",2:"That's a whole rack (or several), not one node.",3:"Power is one of the first constraints in every AI facility design."}},

{domain:2, q:"Why is liquid cooling increasingly standard for high-density GPU racks?",
 opts:["It looks impressive during tours","Air cannot economically remove 40-100+ kW per rack; liquid carries heat far more efficiently at these densities","Liquid cooling is cheaper to install than fans","Regulations ban air cooling"],
 ans:1, exp:"Beyond roughly 30-40 kW per rack, air cooling needs extreme airflow and still struggles. Direct-liquid or rear-door heat exchangers handle modern GPU rack densities and improve PUE.",
 correct:"Correct — at AI densities, physics favors liquid.",
 wrong:{0:"Aesthetics don't drive facility engineering.",2:"Install cost is higher; operating efficiency and feasibility justify it.",3:"No such regulation exists — it's thermodynamics."}},

{domain:2, q:"What does PUE measure?",
 opts:["GPU utilization percentage","Total facility power divided by IT equipment power — how much overhead cooling/distribution adds","Peak user experience","Power used per epoch"],
 ans:1, exp:"Power Usage Effectiveness of 1.0 would mean every watt goes to computing. A PUE of 1.5 means 50% extra for cooling and distribution. Efficient AI datacenters push toward ~1.1–1.2, often with liquid cooling.",
 correct:"Right — facility overhead ratio; lower is better, 1.0 is the ideal.",
 wrong:{0:"GPU utilization is measured by DCGM, not PUE.",2:"It's an engineering metric, not UX.",3:"Training energy per epoch is a workload metric, not a facility one."}},

{domain:2, q:"Which storage profile fits deep-learning training datasets best?",
 opts:["A single NFS server on 1 GbE","A parallel filesystem (e.g., Lustre) striping data across many storage servers, delivering tens of GB/s to many nodes at once","USB drives attached per node","Cloud cold-archive storage mounted directly"],
 ans:1, exp:"Hundreds of GPUs reading shuffled samples simultaneously demand parallel throughput. Parallel filesystems stripe files across servers so aggregate bandwidth scales; a single NFS head becomes the classic sawtooth-utilization bottleneck.",
 correct:"Correct — parallel filesystems exist precisely for this many-readers pattern.",
 wrong:{0:"One server and 1 GbE starves even a single DGX.",2:"Local USB media can't be shared, synced, or fed fast enough.",3:"Archive tiers have minutes-scale latency — for retention, not training reads."}},

{domain:2, q:"What is GPUDirect Storage (GDS)?",
 opts:["A cloud backup service for GPUs","DMA directly between storage (NVMe/parallel FS) and GPU memory, bypassing the CPU bounce buffer","A RAID controller brand","Storing model weights inside the GPU driver"],
 ans:1, exp:"GDS (via cuFile) lets storage DMA straight into GPU memory instead of staging through system RAM. Data-heavy pipelines gain throughput and lose CPU overhead — the storage twin of GPUDirect RDMA.",
 correct:"Right — the direct storage-to-GPU data path.",
 wrong:{0:"Backup services are unrelated.",2:"It's a data-path technology, not hardware branding.",3:"Drivers don't store datasets."}},

{domain:2, q:"Why do large training jobs write periodic checkpoints, and what does that imply for storage?",
 opts:["To decorate dashboards; no storage impact","To resume after failures without losing progress — creating bursty, large sequential writes the storage system must absorb quickly","Because Slurm requires it by default","To reduce GPU memory usage during training"],
 ans:1, exp:"A multi-week job that fails at 90% without checkpoints restarts from zero. Checkpointing a large model dumps tens to hundreds of GB at once; if storage absorbs it slowly, thousands of GPUs sit idle during every save.",
 correct:"Correct — failure insurance whose write bursts size the storage system.",
 wrong:{0:"Checkpoints are operational necessity, and their bursts are a real storage sizing input.",2:"Schedulers don't force checkpoints; frameworks/jobs implement them.",3:"Checkpoints protect progress; they don't reduce memory pressure."}},

{domain:2, q:"A cluster design assigns one 400 Gb/s NIC per GPU (8 per node). What justifies this ratio?",
 opts:["Marketing symmetry","At scale, all-reduce bandwidth per GPU must keep pace with compute; one NIC per GPU keeps inter-node gradient exchange from throttling training","NICs are cheaper than cables","It reduces the node's power draw"],
 ans:1, exp:"As jobs span more nodes, each GPU's share of gradient traffic must cross the fabric. Sizing one high-speed NIC per GPU (the DGX/SuperPOD pattern) keeps communication from becoming the limiter that idles compute.",
 correct:"Right — network bandwidth scaled to compute so gradients never queue behind a shared pipe.",
 wrong:{0:"The ratio comes from collective-traffic math, not aesthetics.",2:"Cost goes up with NIC count; the spend buys unblocked scaling.",3:"More NICs draw more power, not less."}},

{domain:2, q:"What is a BlueField DPU?",
 opts:["A GPU with extra VRAM","A data processing unit — an Arm-based SmartNIC that offloads networking, storage, and security stacks from the host CPU","A power supply module","A CUDA debugging tool"],
 ans:1, exp:"The DPU runs infrastructure services (virtual switching, storage initiators, firewalls, telemetry) on its own cores, isolating them from tenants and returning host CPUs to application work. DOCA is its SDK.",
 correct:"Correct — infrastructure-on-a-card, freeing host CPUs for the actual workload.",
 wrong:{0:"DPUs complement GPUs; they aren't GPUs.",2:"Power delivery is unrelated.",3:"Debugging tools live in the CUDA toolkit."}},

{domain:2, q:"Which scenario most strongly favors on-prem GPU infrastructure over cloud?",
 opts:["A two-week proof of concept","Sustained multi-year high utilization plus strict data-residency requirements","Unpredictable, bursty experimentation","A team with no datacenter staff"],
 ans:1, exp:"Cloud premiums pay off for elasticity; steady 24/7 utilization for years makes owned hardware substantially cheaper (TCO), and residency/compliance constraints may require physical control regardless.",
 correct:"Right — steady high utilization plus data control is the on-prem sweet spot.",
 wrong:{0:"Short POCs are exactly what cloud rental is for.",2:"Bursty loads waste owned hardware; elasticity wins.",3:"No ops staff argues for cloud, where the provider runs the platform."}},

{domain:2, q:"What is the main scaling unit concept behind DGX SuperPOD?",
 opts:["Add one GPU at a time as needed","Grow in validated blocks (scalable units of nodes + switches + storage) with predictable performance at each step","Buy a new datacenter per model","Randomly attach servers until jobs fail"],
 ans:1, exp:"SuperPOD reference architecture expands in engineered increments — e.g., 32-node scalable units with their leaf/spine networking and storage sized together — so each expansion behaves predictably instead of exposing new bottlenecks.",
 correct:"Correct — pre-validated building blocks, not ad-hoc accretion.",
 wrong:{0:"Single-GPU increments can't maintain fabric and storage ratios.",2:"Facilities grow in pods and rows long before whole new buildings.",3:"Unplanned growth is precisely what reference architectures prevent."}},

{domain:2, q:"Which component pair enables multi-node NCCL traffic to bypass host CPUs entirely?",
 opts:["GPUDirect RDMA with an RDMA-capable NIC (InfiniBand/RoCE)","SATA and USB 3.0","Bluetooth and NFC","HDMI and DisplayPort"],
 ans:0, exp:"With GPUDirect RDMA, the HCA/NIC DMAs GPU memory straight onto the wire and into the remote GPU's memory. Host CPUs and system RAM stay out of the data path — the foundation of scalable collectives.",
 correct:"Right — RDMA NIC + GPUDirect is the CPU-bypass pair.",
 wrong:{1:"Storage/peripheral buses play no role in the network path.",2:"Personal-area radios are irrelevant at datacenter scale.",3:"Display outputs don't carry cluster traffic."}},

{domain:2, q:"A 4-node training job runs at 92% scaling efficiency, but 32 nodes drops to 61%. Which subsystem is the first suspect?",
 opts:["GPU video encoders","The inter-node network fabric (bandwidth, congestion, or topology imbalance)","Keyboard latency","BIOS splash screen settings"],
 ans:1, exp:"Scaling efficiency that decays with node count is the signature of communication limits: all-reduce time grows with the fabric's weakest property — oversubscription, congestion, or broken rails — while per-GPU compute stays constant.",
 correct:"Correct — decay with scale points at the fabric before anything else.",
 wrong:{0:"NVENC video engines are idle in training.",2:"Human input devices are not in the loop.",3:"Boot cosmetics can't affect steady-state training."}},

{domain:2, q:"Why might an AI cluster reserve separate network fabrics for compute (east-west) and storage traffic?",
 opts:["To double cable colors","So bursty checkpoint/dataset I/O cannot congest latency-sensitive gradient collectives","Because switches only support one protocol each","To comply with fire codes"],
 ans:1, exp:"Storage bursts (checkpoints, dataset prefetch) and all-reduce traffic have clashing patterns. Separating fabrics — or at least isolating classes with QoS — keeps a checkpoint from stalling every training step in the pod.",
 correct:"Right — isolation keeps storage bursts from stepping on collectives.",
 wrong:{0:"Aesthetics don't shape fabric design.",2:"Modern switches handle multiple traffic types; the isolation is deliberate engineering.",3:"Fire codes govern cabling safety, not traffic classes."}},

{domain:2, q:"What does 'oversubscription' mean in a leaf-spine network, and what does AI training prefer?",
 opts:["Selling more cloud accounts than GPUs","Uplink bandwidth less than downlink capacity (e.g., 3:1); AI fabrics prefer 1:1 non-blocking designs","Subscribing to multiple vendor newsletters","Assigning multiple IPs per NIC"],
 ans:1, exp:"A 3:1 oversubscribed leaf has a third of the uplink bandwidth its ports could demand — fine for average enterprise traffic, hostile to synchronized all-reduce bursts where every node transmits at once. Training fabrics aim for non-blocking 1:1.",
 correct:"Correct — collectives make every port burst simultaneously, so non-blocking wins.",
 wrong:{0:"Commercial subscriptions are a different concept.",2:"Newsletters, no.",3:"IP addressing is unrelated to bandwidth ratios."}},

{domain:2, q:"Which memory technology feeds datacenter GPUs, and why?",
 opts:["DDR4 SO-DIMMs for easy replacement","Stacked HBM (High-Bandwidth Memory) co-packaged with the GPU, supplying terabytes/second of bandwidth","microSD cards in RAID","Optical memory crystals"],
 ans:1, exp:"Thousands of cores consume data faster than socketed DRAM can deliver. HBM stacks sit millimeters from the die on a silicon interposer, giving H100-class GPUs ~3 TB/s — an order of magnitude beyond CPU memory bandwidth.",
 correct:"Right — co-packaged stacked HBM is what keeps the cores fed.",
 wrong:{0:"Socketed laptop DRAM lacks the bandwidth by ~30x.",2:"Flash cards are storage, far too slow for working memory.",3:"Science fiction, for now."}},

{domain:2, q:"A tenant needs hard isolation between two teams sharing one H100, including separate memory and fault domains. Which technology?",
 opts:["Time-slicing","MIG (Multi-Instance GPU)","Setting different shell prompts","CUDA_VISIBLE_DEVICES alone"],
 ans:1, exp:"MIG physically partitions the GPU — SMs, memory slices, and L2 — into up to 7 instances with independent fault isolation: a crash in one instance can't take down another. Time-slicing shares everything and isolates nothing.",
 correct:"Correct — MIG is the hardware partition with real fault isolation.",
 wrong:{0:"Time-slicing alternates full access; one tenant's fault or memory pressure hits everyone.",2:"Cosmetic shell changes isolate nothing.",3:"Environment variables hide devices but share the hardware underneath."}},

{domain:2, q:"Why does adding GPUs to a training job NOT linearly reduce time-to-train past a certain point?",
 opts:["GPUs get tired","Communication overhead (gradient synchronization) grows with scale and eventually rivals the shrinking per-GPU compute time","Datasets shrink as GPUs are added","Electricity providers throttle large jobs"],
 ans:1, exp:"Amdahl-style limits: per-step compute shrinks as you divide the batch, but every step still ends in a synchronized all-reduce whose cost grows with participants. When comm time ≈ compute time, scaling flattens.",
 correct:"Right — synchronization is the serial fraction that caps scaling.",
 wrong:{0:"Silicon doesn't fatigue.",2:"The dataset is constant; only its division changes.",3:"Utilities bill, they don't throttle collectives."}},

{domain:2, q:"What role does PCIe play in a modern GPU server that also has NVLink?",
 opts:["No role at all","Connects GPUs to CPUs, NICs, and storage — the general-purpose bus — while NVLink handles GPU-to-GPU","Replaces the power cables","Only used during boot"],
 ans:1, exp:"PCIe remains the host connectivity: CPU-to-GPU command traffic, NIC and NVMe attachment. NVLink supplements it specifically for peer GPU traffic, which would otherwise saturate PCIe's far lower bandwidth.",
 correct:"Correct — PCIe is the general road network; NVLink is the GPU express lane.",
 wrong:{0:"Every GPU still enumerates and talks to the host over PCIe.",2:"Power arrives via dedicated connectors/busbars.",3:"It's active constantly — kernel launches and NIC DMA ride on it."}},

{domain:2, q:"Which statement about AI cluster capacity planning is most accurate?",
 opts:["Buy exactly the GPUs needed today; grow one card at a time","Plan power, cooling, network, and storage together — GPUs are only one axis, and any single undersized subsystem strands the others","Network can be added later without design impact","Storage sizing is independent of GPU count"],
 ans:1, exp:"A pod is a balanced system: 10 kW/node power, matching cooling, non-blocking fabric per GPU, and storage throughput scaled to feed every node. Undersizing any one leaves expensive GPUs idle.",
 correct:"Right — balanced subsystems or stranded investment.",
 wrong:{0:"Piecemeal growth breaks the ratios (fabric radix, PDU capacity) that make pods perform.",2:"Fabric topology is the hardest thing to retrofit — it's designed first, not last.",3:"More GPUs read more data; storage throughput scales with the fleet."}},

{domain:2, q:"What is the purpose of a TOR/leaf switch pair per rack in AI pods?",
 opts:["Decoration and cable weight","Aggregating each rack's NICs into the spine fabric with redundancy; its port speed and uplink ratio set the rack's usable bandwidth","Heating the cold aisle","Storing checkpoint data"],
 ans:1, exp:"Leaf switches terminate the rack's NIC links and uplink into spines. Their radix, speed, and oversubscription ratio literally define how much of the rack's compute can talk out simultaneously — core sizing parameters of the pod.",
 correct:"Correct — the leaf layer is where a rack's bandwidth budget is set.",
 wrong:{0:"They're the most performance-critical boxes in the rack.",2:"Heat is a byproduct, not a purpose.",3:"Switches forward; storage systems store."}},

{domain:2, q:"Why are AI datacenter racks often deployed half-empty (by rack units)?",
 opts:["Aesthetics of symmetry","The rack's power/cooling budget is exhausted long before its physical space — 3 DGX nodes can consume a 30 kW feed","Servers need room to expand physically","Fire code requires empty slots"],
 ans:1, exp:"At ~10 kW per node, a standard feed supports only a few systems even though the rack could physically hold ten or more. Density is capped by watts, not rack units — driving liquid cooling and higher-amperage feeds.",
 correct:"Right — watts run out before rack units do.",
 wrong:{0:"Layouts follow power math, not looks.",2:"Chassis don't grow after installation.",3:"Codes constrain clearances, not slot occupancy."}},

// ============ DOMAIN 3 — AI OPERATIONS ============
{domain:3, q:"Which tool is the standard for health monitoring and telemetry of datacenter NVIDIA GPUs?",
 opts:["Task Manager","DCGM (Data Center GPU Manager)","GeForce Experience","top"],
 ans:1, exp:"DCGM provides field-level telemetry (utilization, memory, ECC, XIDs, thermals, power), active health checks, and policy hooks. Its exporter feeds Prometheus/Grafana — the standard production monitoring chain.",
 correct:"Correct — DCGM is the datacenter GPU monitoring layer.",
 wrong:{0:"Task Manager is a desktop tool without GPU health depth.",2:"GeForce Experience targets gaming PCs, not clusters.",3:"top sees CPU processes; it knows nothing of ECC or XIDs."}},

{domain:3, q:"nvidia-smi shows a GPU at 100% utilization, yet the training job progresses barely faster than CPU-only. What subtlety explains this?",
 opts:["nvidia-smi always lies","GPU 'utilization' counts any kernel activity per sample window — tiny inefficient kernels can read 100% while doing little useful math; check SM occupancy/tensor activity via DCGM or profilers","The GPU is mining cryptocurrency in the background","100% utilization guarantees maximum performance"],
 ans:1, exp:"The utilization metric is coarse: 'a kernel was resident during the sample'. A job bottlenecked on tiny ops or data starvation can pin it at 100% while Tensor Cores idle. DCGM's SM_ACTIVE/TENSOR_ACTIVE or Nsight reveal the truth.",
 correct:"Right — coarse metric; deeper counters distinguish busy from productive.",
 wrong:{0:"The tool reports accurately — the metric definition is just coarse.",2:"Unexplained load merits investigation, but the metric subtlety is the standard explanation.",3:"That inversion is exactly the trap this question tests."}},

{domain:3, q:"What is the operational meaning of a rising SBE (single-bit ECC) trend on one GPU?",
 opts:["Nothing — corrected errors never matter","Early warning: correction is masking degrading memory; trend it, and plan proactive drain/RMA before a DBE strikes","The GPU is overclocked","The job's code has a bug"],
 ans:1, exp:"Each SBE was corrected — jobs are safe today. But an accelerating SBE curve on one card is how memory failure announces itself before an uncorrectable DBE kills a job. Operators watch the derivative, not just the count.",
 correct:"Correct — corrected today, predictive of tomorrow's hard failure.",
 wrong:{0:"Individually harmless, but the trend is one of the best failure predictors available.",2:"Datacenter GPUs run at fixed clocks; ECC trends indicate hardware wear.",3:"Application bugs can't flip DRAM bits — that's physics/hardware."}},

{domain:3, q:"In Slurm, what does GRES configuration accomplish?",
 opts:["Renames the cluster","Declares Generic RESources (like gpu:8) per node so the scheduler can allocate GPUs to jobs that request them","Encrypts job scripts","Sets the message of the day"],
 ans:1, exp:"gres.conf/slurm.conf declare each node's GPUs; jobs request --gres=gpu:4 and Slurm tracks allocation, binds devices, and prevents oversubscription. Without GRES, Slurm schedules CPUs blind to GPUs.",
 correct:"Right — GRES is how Slurm knows and allocates GPUs.",
 wrong:{0:"Cluster naming is elsewhere.",2:"No encryption involved.",3:"MOTD is cosmetic; GRES is scheduling substance."}},

{domain:3, q:"What does the NVIDIA GPU Operator automate on Kubernetes?",
 opts:["Writing training code","Installing/managing the driver, container toolkit, device plugin, DCGM exporter, and MIG configuration across nodes as containers","Purchasing GPUs from vendors","Converting CPUs into GPUs"],
 ans:1, exp:"The Operator turns GPU node provisioning into declarative K8s state: driver daemonsets, device plugin (exposes nvidia.com/gpu), monitoring exporter, MIG manager. Nodes join the cluster and become GPU-schedulable automatically.",
 correct:"Correct — the whole GPU software stack, operated as Kubernetes resources.",
 wrong:{0:"Application code remains the team's job.",2:"Procurement is human work.",3:"No software converts silicon."}},

{domain:3, q:"A job requests 4 GPUs on a K8s cluster where every node has 8 GPUs but each is 6/8 allocated. Pods stay Pending. Why?",
 opts:["Kubernetes is broken","GPU requests are per-node resources: no single node has 4 free, even though 8+ exist cluster-wide; fragmentation blocks placement","GPUs need reboot weekly","The pod forgot a password"],
 ans:1, exp:"Extended resources bind on one node — requests can't span machines. 2 free GPUs on four different nodes satisfy nothing for a 4-GPU pod. Answers: bin-packing policies, defragmentation, or gang-aware schedulers.",
 correct:"Right — cluster-wide totals are irrelevant; a single node must fit the request.",
 wrong:{0:"The scheduler is correctly refusing an unsatisfiable placement.",2:"Reboots have nothing to do with placement math.",3:"Authentication is not part of scheduling."}},

{domain:3, q:"When comparing MIG, vGPU, and time-slicing for sharing GPUs, which mapping is correct?",
 opts:["MIG: hardware partitions with fault isolation · vGPU: virtualized GPUs for VMs with licensing · time-slicing: software turn-taking, no isolation","They are three names for the same feature","Time-slicing offers the strongest isolation","vGPU works without any license"],
 ans:0, exp:"MIG slices silicon (up to 7 isolated instances). vGPU presents virtual GPUs into VMs via licensed host software (can sit atop MIG). Time-slicing merely alternates whole-GPU access — cheapest, zero isolation.",
 correct:"Correct — hardware partition vs licensed VM virtualization vs software turn-taking.",
 wrong:{1:"They differ fundamentally in isolation, licensing, and mechanism.",2:"Time-slicing is the weakest isolation of the three — neighbors affect each other freely.",3:"vGPU requires NVIDIA licensing (e.g., via AI Enterprise)."}},

{domain:3, q:"Prometheus shows DCGM_FI_DEV_GPU_TEMP climbing across all GPUs in one rack simultaneously. Individual GPU faults are unlikely. What should operations check first?",
 opts:["Reinstall drivers on every node","Facility-level cooling for that rack: airflow blockage, CRAC/coolant issue, or hot-aisle recirculation","Rotate all JWT tokens","Update Kubernetes"],
 ans:1, exp:"Correlated thermal rise across a whole rack points above the servers: cooling delivery. Ruling out facility causes first avoids chasing sixteen phantom GPU 'failures' that share one airflow problem.",
 correct:"Right — correlated symptoms mean shared cause; check the rack's cooling path.",
 wrong:{0:"Software can't heat every GPU in a rack at once.",2:"Auth systems don't move heat.",3:"Orchestrator versions don't change thermodynamics."}},

{domain:3, q:"Why do operators drain a node instead of killing jobs when maintenance is needed?",
 opts:["Draining is more dramatic","Drain stops NEW work while letting running jobs finish, converting maintenance into a zero-casualty event","Killing jobs is impossible","Drained nodes run faster"],
 ans:1, exp:"scontrol update state=drain (or kubectl cordon+drain) removes the node from scheduling while respecting running work. Users lose nothing; the operator gets the node — the difference between maintenance and an incident.",
 correct:"Correct — stop the inflow, let current work land, then service the node.",
 wrong:{0:"The point is minimal drama.",2:"Killing is easy — and that's the problem.",3:"Drain affects scheduling, not node performance."}},

// ---- Extended XID coverage: application faults, memory spectrum, GSP ----

{domain:3, q:"dmesg shows 'Xid 13: Graphics Exception' every time one researcher's custom CUDA kernel runs. Other jobs on the same GPU complete cleanly. What is the correct first action?",
 opts:["Drain the node and open an RMA for the GPU","Treat it as an application bug — have the researcher debug the kernel (illegal instruction or out-of-range address)","Reset the GPU with nvidia-smi --gpu-reset","Replace the NVLink cable"],
 ans:1, exp:"XID 13 is a graphics engine exception, most often raised when the running application executes an illegal instruction or touches an out-of-range address. The strongest evidence here is correlation: it follows one specific job while everything else runs clean. That pattern says 'bug in the code', not 'broken silicon'.",
 correct:"Right — one job triggers it, other jobs don't: that correlation points at the application, not the hardware.",
 wrong:{0:"RMA is for hardware-integrity evidence like DBEs or failed page retirement. A fault that follows one specific application around is the application's bug.",2:"A reset clears state but the exception will return the next time the faulty kernel runs — the root cause is in the code.",3:"Nothing here implicates the interconnect; XID 13 is an engine/application exception, not a link error."}},

{domain:3, q:"A training job dies with 'CUDA error: an illegal memory access was encountered' and dmesg logs XID 31 on that GPU. DCGM shows zero ECC errors. What happened?",
 opts:["The GPU memory is failing and the node must be drained","The application performed an invalid GPU memory access (page fault) — debug it with compute-sanitizer","The GPU fell off the PCIe bus","The NVIDIA driver needs a downgrade"],
 ans:1, exp:"XID 31 is a GPU memory page fault: the application asked the GPU to read or write an address it had no right to touch. It is overwhelmingly an application bug — the GPU-side equivalent of a segfault. Clean ECC counters confirm the memory hardware is fine. Tools like compute-sanitizer pinpoint the offending access.",
 correct:"Correct — XID 31 with clean ECC counters is a software segfault on the GPU, not failing memory.",
 wrong:{0:"Failing memory announces itself through ECC counters and XID 48/63/64/92-class events. Zero ECC errors plus a page fault points at the application's addressing, not the DRAM.",2:"A GPU that falls off the bus raises XID 79 and disappears from nvidia-smi entirely — this GPU is still present and reporting.",3:"Driver version is not implicated by a page fault that maps to an application's illegal access."}},

{domain:3, q:"dmesg shows XID 43 on GPU 2. The job that was running there is gone, but nvidia-smi looks normal and other jobs on the node keep running. What does XID 43 tell the operator?",
 opts:["The GPU is about to fall off the bus","A user application hit an error and was stopped, and the GPU recovered — no hardware action needed","Uncorrectable memory corruption occurred","The node's cooling has failed"],
 ans:1, exp:"XID 43 means a user application error caused its GPU work to be stopped, while the GPU itself recovered and continued serving other contexts. It is an application-death notice, not a hardware alarm — the operational response is to let the job owner debug, not to touch the node.",
 correct:"Right — XID 43 reports a job casualty, not a node casualty.",
 wrong:{0:"Bus loss is XID 79 and takes the whole GPU with it — here the GPU is still healthy and serving other work.",2:"Uncorrectable memory events raise XID 48 (or 94/95 on containment-capable GPUs) and show in ECC counters.",3:"Thermal problems show as throttling and temperature evidence, not as a single application being stopped."}},

{domain:3, q:"An operator kills a hung training job with SIGKILL. Seconds later dmesg logs XID 45 on its GPUs. How should this XID be read?",
 opts:["As proof the GPUs were the reason the job hung","As preemptive cleanup: the driver tore down the killed job's channels — a context signal, not a root cause","As an uncorrectable ECC event requiring a drain","As an NVLink CRC failure"],
 ans:1, exp:"XID 45 is the driver's cleanup record: a job's GPU channels were preempted/torn down, commonly because the process was killed or a preceding fault forced cleanup. Its diagnostic value is context — look at what happened immediately before it. Here the operator's own SIGKILL explains it completely.",
 correct:"Correct — XID 45 documents the cleanup you caused, not a new fault.",
 wrong:{0:"The XID followed the kill, it did not precede the hang — it is an effect of the operator's action, not evidence about the original cause.",2:"ECC trouble has its own codes (48, 63, 64, 92, 94, 95) and counter evidence; a teardown record is not a memory event.",3:"NVLink CRC problems raise XID 74 with link-counter evidence, unrelated to killing a process."}},

{domain:3, q:"dmesg logs XID 63 ('row remapping event recorded') on an A100. Jobs are still running normally. What is the correct operational response?",
 opts:["Nothing — the message is purely informational and can be ignored permanently","Schedule a drain and GPU reset at the next maintenance window so the recorded row remap takes effect","Open an RMA immediately — the GPU has failed","Kill all jobs on the node right now"],
 ans:1, exp:"XID 63 means the GPU recorded a degraded memory row for remapping to spare cells — the card's self-healing mechanism. The remap only takes effect after a GPU reset, so the right move is planned: drain the node, reset the GPU, verify with nvidia-smi -q that the remap completed. It is maintenance to schedule, not an emergency.",
 correct:"Right — self-healing was recorded but needs a reset to apply: plan it, don't panic.",
 wrong:{0:"Ignoring it forever leaves the bad row in service; the remap never takes effect without a reset, and the row can escalate to uncorrectable errors.",2:"RMA is the XID 64 path — when remapping FAILS. A successful remap recording means the GPU is handling it as designed.",3:"Nothing is uncorrectable yet; killing live jobs turns a scheduled-maintenance signal into a self-inflicted incident."}},

{domain:3, q:"A GPU logs XID 64 ('row remapping failure'). How does the response differ from XID 63?",
 opts:["It doesn't — 63 and 64 mean the same thing","XID 64 means the self-healing path itself failed, so the GPU moves from 'schedule a reset' to the RMA/replacement path","XID 64 is less serious because the memory was already repaired","XID 64 only affects NVLink traffic"],
 ans:1, exp:"XID 63 records a successful remap request (fixed by a reset). XID 64 means the GPU tried to retire/remap the degraded row and could not — its spare resources or the remap mechanism failed. When the self-healing machinery breaks, the hardware-replacement path is the safe conclusion: drain the node and open an RMA.",
 correct:"Correct — 63 is healing scheduled, 64 is healing failed: that failure is what justifies the RMA.",
 wrong:{0:"They are opposite outcomes of the same mechanism: one recorded a fix, the other failed to apply one.",2:"Nothing was repaired — the repair is exactly what failed, which is why it is MORE serious than 63.",3:"Row remapping is about GPU DRAM, not the interconnect; NVLink faults live in the XID 74 family."}},

{domain:3, q:"DCGM alerts on XID 92 ('high single-bit ECC error rate') for GPU 5, but every error is corrected and no DBEs exist. What is the right posture?",
 opts:["Drain the node this minute — data corruption is occurring","Treat it as an early-warning trend: tighten monitoring and plan maintenance per policy, since correction is still winning","Disable ECC to stop the alerts","Reflash the GPU firmware immediately"],
 ans:1, exp:"XID 92 says the correction machinery is working overtime — an elevated rate of corrected single-bit errors. Nothing has been corrupted, but healthy memory doesn't need constant correction, so the trend is a leading indicator. The response is operational vigilance: watch SBE/DBE counters, check for row-remap events, and plan service according to the fleet's failure policy.",
 correct:"Right — corrected means safe for now; the elevated rate is what earns the GPU a watch list spot.",
 wrong:{0:"Corrected errors are exactly that — corrected. No data was harmed; an emergency drain answers a threat that hasn't materialized.",2:"Disabling ECC silences the smoke detector because it keeps beeping — you lose correction AND the early warning while the memory keeps degrading.",3:"Firmware isn't implicated by aging memory cells; reflashing adds risk without addressing the trend."}},

{domain:3, q:"On an H100, dmesg shows XID 94 ('contained ECC error') and one inference service crashed. nvidia-smi shows the GPU healthy. What does 'contained' buy the operator?",
 opts:["Nothing — the whole node must still be rebooted","The hardware isolated the uncorrectable error to the one process that touched the bad data: restart that workload, let the GPU keep serving the rest","It means the error was corrected and no process was affected","It converts the fault into a network problem"],
 ans:1, exp:"Error containment on A100/H100-class GPUs walls off an uncorrectable ECC error so only the process consuming the poisoned data is terminated. XID 94 is the success report: the blast radius was one workload. Restart the affected service, note the event (a row remap often follows), and keep the GPU in service — that is the feature working as designed.",
 correct:"Correct — containment shrank an incident to a single process restart.",
 wrong:{0:"Rebooting the node discards the entire benefit of containment; the GPU and its other workloads are explicitly safe to continue.",2:"The error was UNcorrectable — that's why a process died. Contained means isolated, not repaired.",3:"ECC containment is a memory mechanism; nothing about it involves the network."}},

{domain:3, q:"The same H100 later logs XID 95 ('uncontained ECC error'). How does the response change from XID 94?",
 opts:["It doesn't — 94 and 95 are handled identically","Containment failed, so the GPU's wider state can't be trusted: drain the node and reset/reboot before it serves new work","XID 95 is milder because the error dissipated on its own","Only the network stack needs restarting"],
 ans:1, exp:"XID 95 means the containment attempt failed — the uncorrectable error's reach could not be limited to one process, so every context on that GPU is suspect. The response escalates to the XID 48-style path: drain the node, reset the GPU or reboot, and verify (retired pages, remap status, recurrence) before returning it to service.",
 correct:"Right — 94 is containment succeeding, 95 is containment failing: the failure is what forces the drain-and-reset.",
 wrong:{0:"They are opposite outcomes: 94 limits the damage to one process; 95 means that limit failed and the whole GPU's state is in question.",2:"Uncontained is the worse outcome — the poisoned data's reach is unknown, which is precisely why the GPU can't be trusted.",3:"ECC containment concerns GPU memory state; restarting network services would address none of it."}},

{domain:3, q:"A node's GPU stops responding; dmesg shows XID 119 ('GSP RPC timeout'). nvidia-smi hangs when queried. What fault family is this, and what is the recovery path?",
 opts:["An application page fault — the job owner should debug their kernel","A GSP firmware hang: the GPU System Processor stopped answering the driver — recover with a GPU reset or node reboot, and treat repeats as a driver/firmware issue","A classic thermal throttle — improve airflow","An InfiniBand fabric failure"],
 ans:1, exp:"Modern drivers offload work to the GSP (GPU System Processor) firmware on the card. XID 119 means an RPC to that firmware timed out — the GPU can look completely frozen even though the compute silicon is fine. Recovery is a GPU reset or node reboot; recurring GSP timeouts point at driver/firmware versions (updating, or in some fleets disabling GSP mode) rather than failed hardware.",
 correct:"Correct — a firmware-hang family of its own: reset to recover, and chase driver/firmware versions if it repeats.",
 wrong:{0:"Application page faults are XID 31 and kill one job; they don't make nvidia-smi itself hang.",2:"Thermal problems show as temperature and clock evidence with the GPU still responsive; a GSP timeout is unresponsiveness, not slowdown.",3:"The fabric moves data between nodes; a GPU that won't answer its own driver is faulting well below the network layer."}},

{domain:3, q:"A GB200 rack logs 'Xid 149, NETIR_LINK_DOWN Fatal' on one GPU. An operator who trained on H100 fleets has never seen this code. What is it?",
 opts:["A brand-new fault family with no older equivalent","The Blackwell/NVLink5 generation's fatal NVLink error — the same interconnect fault family that H100-era fleets reported as XID 74","An uncorrectable ECC memory error","A GSP firmware timeout"],
 ans:1, exp:"XID 149 covers NVLink 'NETIR' errors on B100/GB200-class GPUs — link-down, bit-error-rate, and data-error events on NVLink5. The fault family is the one operators already know from XID 74: the GPU-to-GPU link path is unhealthy. The investigation is familiar too — link telemetry, cable/connector signal integrity, and the peer GPU or switch — while the exact recovery (reset vs. ignore) depends on the reported subcode.",
 correct:"Right — same fabric-fault family, new code number on the new generation. Knowing the families beats memorizing the numbers.",
 wrong:{0:"It maps directly onto the known NVLink fault family; only the code number and subcode detail are new to the generation.",2:"ECC memory trouble reports under 48/63/64/92/94/95 with counter evidence — a LINK_DOWN message is about the interconnect, not DRAM.",3:"GSP timeouts are XID 119 and make the GPU stop answering its driver; this GPU is responsive and reporting a dead link."}},

{domain:3, q:"Right after a fault, dmesg adds: 'Xid 154, GPU Recovery Action Changed: Node Reboot Required'. What should the operator make of XID 154?",
 opts:["A second independent hardware failure — the node now has two faults to root-cause","An informational companion code: the driver is stating what recovery the preceding fault requires — follow the action it names","A signal that the previous XID was a false alarm","An NVLink cable fault"],
 ans:1, exp:"XID 154 is not a new fault. It is the driver summarizing the recovery consequence of another XID: the message itself names the required action, such as 'GPU Reset Required' or 'Node Reboot Required'. The operator pairs it with the primary fault code for root cause, and takes the recovery action 154 spells out — it removes the guesswork about how far recovery must go.",
 correct:"Correct — 154 is the driver handing you the recovery plan for the fault that preceded it.",
 wrong:{0:"Nothing new failed; 154 is metadata about the previous fault's recovery, so there is still exactly one root cause to chase.",2:"The opposite — it confirms the previous fault was serious enough to change the required recovery action.",3:"Link faults report as XID 74 (or 149 on Blackwell) with link evidence; 154 carries recovery guidance, not a fault of its own."}},
];
